/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.pyoneru.designpattern;

import pl.pyoneru.designpattern.model.Communicator;
import pl.pyoneru.designpattern.model.Quest;
import pl.pyoneru.designpattern.model.REcoDeQuest;
import pl.pyoneru.designpattern.model.User;

public class App {
    public App(){
        REcoDeQuest rq = new REcoDeQuest();

        Communicator slack = new Communicator("Slack", "F44Red", "general");
        Communicator discord = new Communicator("Discord", "F44 Red", "hello world:general");

        rq.addSubscriber(slack);
        rq.addSubscriber(discord);

        User pyoneru = new User("Pyoneru");
        User lazzr = new User("LazzR");
        User onlySlack = new User("OnlySlack");
        User onlyDiscord = new User("OnlyDiscord");

        slack.addSubscriber(pyoneru);
        slack.addSubscriber(lazzar);
        slack.addSubscriber(onlySlack);
        
        discord.addSubscriber(pyoneru);
        discord.addSubscriber(lazzar);
        discord.addSubscriber(onlyDiscord);

        rq.setQuest(new Quest(3, "Design Pattern", "Implement someone design pattern"));
        rq.notifySubscribers();
    }

    public static void main(String[] args) {
        new App();
    }
}
